import Head from "next/head";
import { Footer } from "src/components/Footer";
import { Main } from "src/components/Main";
import { Header } from "src/components/Header";

const About = (props) => {
  const {
    count,
    isShow,
    handleClick,
    handleClickDec,
    handleDisplay,
    text,
    array,
    handleChangeText,
    handleAdd,
  } = props;

  return (
    <div className="min-h-full px-2 flex flex-col justify-center items-center">
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {isShow ? (
        <div className="flex gap-4 justify-center items-center">
          <button
            className="px-4 py-2 border rounded-full border-white bg-gray-400 hover:bg-gray-50"
            onClick={handleClick}
          >
            +
          </button>
          <p className="text-5xl">{count}</p>
          <button
            className="px-4 py-2 border rounded-full border-white bg-gray-400 hover:bg-gray-50"
            onClick={handleClickDec}
          >
            -
          </button>
        </div>
      ) : null}
      <button onClick={handleDisplay} className="mt-3 py-1 text-base ">
        {isShow ? "非表示" : "表示"}
      </button>
      <input
        type="text"
        value={text}
        onChange={handleChangeText}
        className="my-3 mx-auto p-2"
      />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map((item, index) => {
          return <li key={index}>{item}</li>;
        })}
      </ul>
      <Main page="about" />
      <Footer />
    </div>
  );
};

export default About;
