import Head from "next/head";
import { Header } from "src/components/Header";

const Index = () => {
  return (
    <div className="min-h-full px-2 flex flex-col justify-center items-center">
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1 className="text-4xl m-4">Next.jsで学ぶReact講座</h1>
      <p>JsonPlaceHolderのAPIを色々叩いてみるよ！</p>
    </div>
  );
};

export default Index;
