import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { Header } from "src/components/Header";

const Home = (props) => {
  const [posts, setPosts] = useState([]);

  const getPosts = useCallback(async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts");
    const json = await res.json();
    setPosts(json);
  }, []);

  useEffect(() => {
    getPosts();
  }, [getPosts]);

  console.log(posts);
  return (
    <div className="min-h-full px-2 flex flex-col justify-center items-center">
      <Head>
        <title>Reactの学習</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {posts.length > 0 ? (
        <ol className="list-decimal">
          {posts.map((post) => {
            return <li key={post.id}>{post.title}</li>;
          })}
        </ol>
      ) : null}
    </div>
  );
};

export default Home;
