import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import { Header } from "src/components/Header";
import useSWR from "swr";

const Post = () => {
  const router = useRouter();
  // console.log(router.query.id);

  const { data, error } = useSWR(
    router.query.id
      ? `https://jsonplaceholder.typicode.com/posts/${router.query.id}`
      : null
  );
  console.log({ data, error });
  return (
    <div className="min-h-full px-2 flex flex-col justify-center items-center">
      <Head>
        <title>Reactの学習</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <h1 className="text-2xl">{data?.title}</h1>
        <p>{data?.body}</p>
      </div>
    </div>
  );
};

export default Post;
