import Head from "next/head";
import { Header } from "src/components/Header";
import { Users } from "components/Users";

const UsersIndex = () => {
  return (
    <div className="min-h-full px-2 flex flex-col justify-center items-center">
      <Head>
        <title>Reactの学習</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Users />
    </div>
  );
};

export default UsersIndex;
